### ISSUE TITLE
Ability to alias a secret name

### ISSUE THREAD

**Issue by malikashish8** [malikashish8/uses#3]
Secret names are unique for `uses`. However, there are scenarios when different projects requires secrets with the same name such `AWS_ACCESS_KEY_ID`. Since we cannot have multiple secrets with the same name this is a feature request to add alias to a secret. This alias will be the name that will be used when injecting environment variables.
For example, consider the following config:
```yaml
project:
- name: p1
   secrets:
   - AWS_ACCESS_KEY_ID_P1:
      - alias: AWS_ACCESS_KEY_ID
- name p2
   secrets:
   - AWS_ACCESS_KEY_ID_P2:
      - alias: AWS_ACCESS_KEY_ID
```
This should ensure when `uses p1 code ~/projects/webgoat` is run it injects the variable with name `AWS_ACCESS_KEY_ID`.
